AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Streaming Bedrock Response with FastAPI on AWS Lambda

Parameters:
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - INFO
      - DEBUG
      - WARN
      - ERROR
    Description: The Log Level for the FastAPI Lambda Function

  OwnerTag:
    Type: String
    Description: The value of the owner tag (typically your personal email)

  ProjectTag:
    Type: String
    Default: lambda-response-streaming
    Description: The value of the project tag (typically the name of the project)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          LOG_LEVEL: !Ref LogLevel
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
      Policies:
        - Statement:
            - Sid: BedrockInvokePolicy
              Effect: Allow
              Action:
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
      Tracing: Active
      Tags:
        Owner: !Ref OwnerTag
        Project: !Ref ProjectTag
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: v1

Outputs:
  FastAPIFunctionUrl:
    Description: "Function URL for FastAPI function"
    Value: !GetAtt FastAPIFunctionUrl.FunctionUrl
  FastAPIFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
